cs2610-blog/blog/urls.py
from django.conf.urls import url 

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.mainView, name='main'),
    url(r'^main/$', views.mainView, name='main'),
    url(r'^bio/$', views.bioView, name='bio'),
    url(r'^tech/$', views.techView, name='tech'),
    url(r'^homepage/$', views.homepage.as_view(), name='homepage'),
    url(r'^entry/$', views.entry.as_view(), name='entry'),
    url(r'^archive/$',views.archive.as_view(), name='archive'),
    url(r'^(?P<pk>[0-9]+)/entry/$', views.entry.as_view(), name='entry'),
    url(r'^(?P<blog_id>[0-9]+)/comment/$', views.postComment, name='postComment'),   
    #url(r'^blog/entry/(?P<blog_id>[0-9]+)/$', views.entry.as_view(), name='entry'),
]

cs2610-blog/conversionAPI/urls.py
#Conversion API's urls
from django.conf.urls import url

from . import views

app_name = 'conversionAPI'
urlpatterns = [
    url(r'^convertAPI$', views.convertAPI, name='conversion'),
    url(r'^$', views.index, name='index'),
]

cs2610-blog/cs2610/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import blog
import gold

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include("blog.urls")),
    url(r'^gold/', include("gold.urls")),
    url(r'^gold/', include("conversionAPI.urls")),
]

cs2610-blog/gold/urls.py
#gold's urls
from django.conf.urls import url

from . import views

app_name = 'gold'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

cs2610-blog/blog/models.py
from __future__ import unicode_literals

from django.db import models
from django import forms
from django.utils import timezone

class Blog(models.Model):
    title_blog = models.CharField(max_length=200)
    author_name = models.CharField(max_length=200)
    content_blog = models.TextField()
    post_date = models.DateTimeField('posted date')
    
    def __str__(self):
        return self.content_blog
        
    
class Comments(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=200)
    email_address = models.CharField(max_length=200)
    content_comment = models.TextField()
    post_date = models.DateTimeField('posted date')
    
    def __str__(self):
        return self.content_comment

cs2610-blog/conversionAPI/models.py
#conversionAPI's model
from __future__ import unicode_literals

from django.db import models

# conversion = {'stone' : 6350.2932, 'lbs' : 453.59237, 'kg' : 1000 , 't_oz' : 31.1035} 

# conversion['gram'] = 1
# all to grams

class Unit(models.Model):
    name = models.CharField(max_length=64)
    # Type = models.ForeignKey(name, on_delete=models.CASCADE)
    basis_factor=models.FloatField()
    
    def __str__(self):
        return "[%s] (%s)" % (self.name, self.basis_factor)

# self.Type.name,

cs2610-blog/gold/models.py
#gold's model
from __future__ import unicode_literals

from django.db import models

cs2610-blog/blog/views.py
from django.shortcuts import get_object_or_404,render
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import datetime

from .models import Blog, Comments
    
def mainView(request):
    template_name = 'blog/main.html'
    return render(request,template_name,{'time': datetime.datetime.now()})
    
def bioView(request): 
    template_name = 'blog/bio.html'
    return render(request,template_name,{'time': datetime.datetime.now()})
    
def techView(request):
    template_name = 'blog/tech.html'
    return render(request,template_name,{'time': datetime.datetime.now()})
    
class homepage(generic.ListView):
    model = Blog
    template_name = 'blog/homepage.html'
    
    def get_queryset(self):
        return Blog.objects.order_by('-post_date')[:3]

class archive(generic.ListView):
    model = Blog
    template_name = 'blog/archive.html'
    
    def get_queryset(self):
        return Blog.objects.order_by('-post_date')
        
class entry(generic.DetailView):
    model = Blog
    template_name = 'blog/entry.html'
        
def postComment(request, blog_id):
    # for k, v in request.POST.items():
    #     print k, "=>", v
        
    comment = Comments()
    b = get_object_or_404(Blog, pk=blog_id)
    try:
        comment.nickname = request.POST['nickname']
        comment.content_comment = request.POST['comment']
        comment.email_address = request.POST['email_address']
        comment.post_date = request.POST['post_date']
    except (KeyError, Comments.DoesNotExist):
        return render(request, 'blog/entry.html', {'comment': comment,'error_message': "error",})
    else:
        # comment.blog = b
        comment.save()
    return HttpResponseRedirect(reverse('blog:entry',args=(b.id,)))
    

cs2610-blog/conversionAPI/views.py
from __future__ import unicode_literals
from django.http import HttpResponse

from django.shortcuts import render

import json

from .models import Unit


def convertAPI(request):
    
    response = {}
    
    if not request.GET.has_key('value'):
        response['error_value'] = "variable 'value' not used"
    else:
        value = int(request.GET['value'])
        if(value < 0):
            response['error_value'] = "Usage: value=[non-negative number]"
        else:
            response['value'] = value 
            
    if not request.GET.has_key('from'):
        response['error_from'] = "variable 'from' not used"
    else:
        ufrom = request.GET['from']
        response['from'] = ufrom 
            
    if not request.GET.has_key('to'):
        response['error_to'] = "variable 'to' not used"
    else:
        uto = request.GET['to']
        response['to'] = uto
            
    response['t_oz'] = convert(value,ufrom,uto) 
    
    return HttpResponse(json.dumps(response))
    
def convert(value, ufrom, uto):
    unit_from = Unit.objects.get(name=ufrom)
    unit_to = Unit.objects.get(name=uto)
    
    value = unit_from.basis_factor * value
    value = value * (1.0 / unit_to.basis_factor)
    return value
    
  
    
# def convert(value, ufrom, uto):
#     unit_from = None
#     unit_from = Unit.objects.get(name=request.GET['from'])
#     unit_to = Unit.objects.get(name=request.GET['to'])
#     value_number = request.GET['value']
    
#     value_from = float(request.GET['value'])
#     value_basis = value_number * unit_from.basis_factor
#     value_to = value_basis * (1.0 / unit_to.basis_factor)
# def convert(value, ufrom, uto):
#      value = conversion[ufrom] * value  
#      value = value / conversion[uto] 
#      return value               

def index(request):
    return HttpResponse(request, 'index.html', {})
    

cs2610-blog/gold/views.py
from django.http import HttpResponse
from django.shortcuts import render

import gold

def index(request):
    return render(request, 'gold/main.html', {})
    

cs2610-blog/blog/templates/blog/archive.html
{% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />

<li>
    {% for Blog in object_list %}
        <p>
            <div>
                Title:
                 {{ Blog.title_blog }}
            </div>
            <div>
                {{ Blog.content_blog | truncatewords:200 }} 
            </div>
            <div>
                Author:
                {{ Blog.author_name }}
            </div>
            <div>
                Post date:
                {{ Blog.post_date }}
            </div>
        </p>
    
        {% endfor %}
</li>

cs2610-blog/blog/templates/blog/bio.html
<!DOCTYPE html>
<html lang="zxx">
    <head>
        <title>bio page</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
        
    </head>
    <body class="flex-body">
        <header>
            <p>Bio Page</p>
            <nav>
                <ul>
                    <li><a href="/blog/tech/">tech page</a></li>
                    <li><a href="/blog/main/">main page</a></li>
                </ul>
            </nav>
            <p><img class="pic" src="{% static 'blog/bio.jpg' %}" alt="should be an image here"/> bio image </p>
        
        </header>
        <main class="flex-main">
            <article class="flex-article-bio">
                <h1>
                    client.
                </h1>
                <img class="pic_bio" src="{% static 'blog/steam.jpg' %}" alt="">
                <p>
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                </p>
            </article>
            
            <section>
                <h1> pictures </h1>
                <aside>
                    <img class="side_pic" src="{% static 'blog/excited1.jpg' %}" alt="picture">
                    <img class="side_pic" src="{% static 'blog/excited2.jpg' %}" alt="picture">
                    <img class="side_pic" src="{% static 'blog/excited3.jpg' %}" alt="picture">
                </aside>
            </section>
            
        </main>
        <footer>
            <p>
                Jake Yeagley Copyright me 2017.
            </p>
        </footer>
        
        <p>
            {{ time }}
        </p>
    </body>
</html>

cs2610-blog/blog/templates/blog/entry.html
{% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />

<!--<h1> {{ Blog.title_blog }} </h1>-->

<!--{% if error_message %}-->
<!--<p>-->
<!--    <strong> -->
<!--    {{ error_message }} -->
<!--    </strong>-->
<!--</p>-->
<!--{% endif %}-->

<!--<p> {{ Blog.content_blog }} </p>-->
<!--<p> {{ Blog.post_date }} </p>-->
<!--<p> {{ Blog.author_name }} </p>-->
<!--<p> test </p>-->

<!--- question for Erik -->
<!-- *******
    *********
    *********
    -->
<form action="{% url 'blog:postComment' blog_id %}" method="post">
{% csrf_token %}
    <label for="comment"> add comment </label>
    <input type="textarea" id="comment" name='comment' value='comment'/>
    <input type="submit">Submit</submit>
</form>

{% for blog in Blog.comments_set.all %} 
<div> 
    {{ blog.content_comment }} 
</div>
{% endfor %}

cs2610-blog/blog/templates/blog/homepage.html
{% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />

<li>
    {% for Blog in object_list %}
        <p>
            <div>
                Title:
                 {{ Blog.title_blog }}
            </div>
            <div>
                {{ Blog.content_blog | truncatewords:200 }} 
            </div>
            <div>
                Author:
                {{ Blog.author_name }}
            </div>
            <div>
                Post date:
                {{ Blog.post_date }}
            </div>
        </p>
    
        {% endfor %}
</li>

<p>
   
</p>

cs2610-blog/blog/templates/blog/main.html
<!DOCTYPE html>
<html lang="zxx">
    <head>
        <title> main page </title>
        
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
        
    </head>
    <body class="flex-body">
        <header>
            <p>Main Page</p>
                <nav>
                    <ul>
                        <li><a href="/blog/tech/">tech page</a></li>
                        <li><a href="/blog/bio/">bio page</a></li>
                    </ul>
                </nav>
            <p>
            <img class="pic" src="{% static 'blog/tech.jpg' %}" alt="should be an image here"/> tech image </p>
        </header>
        <main class="flex-main">
            <section class="flex-section">
                <h1> article 1</h1>
                <article>
                    <p>
                       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
                        magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                    </p>
                    <h2> article 2 </h2>
                    <p>
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
                        Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
                        Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
                        Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?
                        Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
                        Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
                        Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
                        Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?
                        Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"
                     </p>   
                   
                        <h3> article 3 </h3>
                        <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
                        Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
                        Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
                        Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?
                        Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"
                        </p>
                    </article>
            </section>
            <aside class="flex-aside">
                <img class="side_pic" src="{% static 'blog/tech1.jpg' %}" alt=""/> 
                <img class="side_pic" src="{% static 'blog/tech2.jpg' %}" alt=""/>
                <img class="side_pic" src="{% static 'blog/tech3.jpg' %}" alt=""/> 
            </aside>
        </main>
        <footer>
            <p>
                Jake Yeagley Copyright me 2017.
            </p>
            <p>
            {{ time }}
        </p>
        </footer>
    </body>
</html>

cs2610-blog/blog/templates/blog/tech.html
<!DOCTYPE html>
<html>
    <head>
        <title> tech page </title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
        
    </head>
    <body class="flex-body">
    <header>
            <p>Tech Page</p>
            <nav>
                <ul>
                    <li><a href="/blog/bio/">bio page</a></li>
                    <li><a href="/blog/main">main page</a></li>
                </ul>
            </nav>
            <p><img class="pic" src="{% static 'blog/gitImage.jpg' %}" alt="should be an image here"> gitImage </p>
        </header>
        <main>
            <article class="flex-article">
                <h1> put this here to please the validator </h1>
                <div class="table table1">
                <table>
                    <tr>
                        <th>git command</th>
                        <th>Description</th>
                        <th>example</th>
                    </tr> 
                    <tbody>
                        <tr>
                            <td> clone </td>
                            <td> Makes a Git repository copy from a remote source. Also adds the original location as a remote so you can fetch from it again and push to it if you have permissions.
                            </td>
                            <td><code>git clone git@github.com:user/test.git</code> </td>
                        </tr>
                        <tr>
                            <td> add </td>
                            <td> Adds files changes in your working directory to your index. </td>
                            <td><code>git add index.html</code></td>
                        </tr>
                        <tr>
                            <td> commit </td>
                            <td> Takes all of the changes written in the index, creates a new commit object pointing to it and sets the branch to point to that new commit.
                            </td>
                            <td> <code>git commit</code> </td>
                        </tr>
                        <tr>
                            <td>  pull </td>
                            <td> Fetches the files from the remote repository and merges it with your local one. This command is equal to the git fetch and the git merge sequence.
                            </td>
                            <td><code>git pull origin</code></td>
                        </tr>
                        <tr>
                            <td> git remote add </td>
                            <td>connects a remote repository to this one</td>
                            <td><code>git remote add origin https://jyeagley@bitbucket.org/jyeagley/cs-2610.git</code></td>
                        </tr>
                        <tr>
                            <td>git push</td>
                            <td>sends changes to a remote repository</td>
                            <td><code>git push -u origin master</code></td>
                        </tr>
                        <tr>
                            <td>git diff</td>
                            <td>tells the difference between commits</td>
                            <td><code>git diff</code></td>
                        </tr>
                        <tr>
                            <td> push </td>
                            <td> Pushes all the modified local objects to the remote repository and advances its branches.
                            </td>
                            <td><code> git push origin master</code></td>
            
                        </tr>
                    </tbody>
                </table>
                </div>
                <div class="table table2">
                <table>
                    <tr>
                        <th>HTML tag</th>
                        <th>Description</th>
                        <th>example</th>
                    </tr> 
                    <tbody>
                        <tr>
                            <td> div </td>
                            <td> used to divide up divions of code, good for using flex box and classes. here's some fluff to make my tables bigger so that the scroll bar will work and I can get a good grade on this assignment.
                            </td>
                            <td><code> div </code></td>
                        </tr>
                        <tr>
                            <td> header </td>
                            <td> used to indicate the head of an article. here's some fluff to make my tables bigger so that the scroll bar will work and I can get a good grade on this assignment. </td>
                            <td><code> header</code></td>
                        </tr>
                        <tr>
                            <td> table </td>
                            <td> used to build a table. here's some fluff to make my tables bigger so that the scroll bar will work and I can get a good grade on this assignment.
                            </td>
                            <td> <code> table </code> </td>
                        </tr>
                        <tr>
                            <td>  tr </td>
                            <td> used to build the rows inside a table. here's some fluff to make my tables bigger so that the scroll bar will work and I can get a good grade on this assignment.
                            </td>
                            <td><code> tr </code></td>
                        </tr>
                        <tr>
                            <td> td </td>
                            <td> used to put data inside a table row. here's some fluff to make my tables bigger so that the scroll bar will work and I can get a good grade on this assignment.</td>
                            <td><code> td </code></td>
                        </tr>
                        <tr>
                            <td> footer </td>
                            <td> used to indicate the bottom end of a page. here's some fluff to make my tables bigger so that the scroll bar will work and I can get a good grade on this assignment.</td>
                            <td><code> footer </code></td>
                        </tr>
                        <tr>
                            <td> section </td>
                            <td> similiar to div and article, used to section off a part of code, good for classes and flexbox. here's some fluff to make my tables bigger so that the scroll bar will work and I can get a good grade on this assignment.</td>
                            <td><code> section </code></td>
                        </tr>
                        <tr>
                            <td> article </td>
                            <td> similiar to section and div.here's some fluff to make my tables bigger so that the scroll bar will work and I can get a good grade on this assignment.
                            </td>
                            <td><code> article </code></td>
            
                        </tr>
                    </tbody>
                </table>
            </div>
                <div class="table table3">
                <table>
                    <tr>
                        <th>CSS code</th>
                        <th>Description</th>
                        <th>example</th>
                    </tr> 
                    <tbody>
                        <tr>
                            <td> bockground-image </td>
                            <td> used to insert an image in the background
                            </td>
                            <td><code> background-image: url("blue-computer-background.jpg" </code> </td>
                        </tr>
                        <tr>
                            <td> background-color </td>
                            <td> used to change the color of the background </td>
                            <td><code> background-color : darkgrey </code></td>
                        </tr>
                        <tr>
                            <td> font-size </td>
                            <td> used to change the size of fonts
                            </td>
                            <td> <code>font-size : 150% </code> </td>
                        </tr>
                        <tr>
                            <td>  font-family </td>
                            <td> used to change the font type
                            </td>
                            <td><code> font-family : serif </code></td>
                        </tr>
                        <tr>
                            <td> font-weight </td>
                            <td> used to change the thickness of fonts </td>
                            <td><code> font-weight : bold </code></td>
                        </tr>
                        <tr>
                            <td> color </td>
                            <td> used to change the color </td>
                            <td><code> color: blue </code></td>
                        </tr>
                        <tr>
                            <td> . </td>
                            <td>used to describe a class so that it can be modified in css</td>
                            <td><code>.class-name</code></td>
                        </tr>
                        <tr>
                            <td> # </td>
                            <td> used to describe a id so that is can be modified in css
                            </td>
                            <td><code> #id-name </code></td>
            
                        </tr>
                    </tbody>
                </table>
            </div>
            </article>
        </main>
        <footer>
            <p>
                Jake Yeagley Copyright me 2017.
            </p>
            <p>
            {{ time }}
        </p>
        </footer>
    </body>
</html>
    

cs2610-blog/conversionAPI/templates/conversionAPI/index.html
<!-- conversion API -->
<html>
    <head>
        <meta charset="utf-8">
        <title>
            converstion API
        </title>
    </head>

    <body>

    <script type="text/javascript">
        var conversion = function()
        {
            var host      = location.protocol + '//' + window.location.host;
            var conReqUrl = host + '/gold/convertAPI?value=' + document.querySelector("#convert").value + '&to=' + document.querySelector("#convert").to + '&from=' + document.querySelector("#convert").From;
            var conReq    = new XMLHttpRequest();
            conReq.open('GET', conReq);
            conReq.responseType = 'json';
            conReq.send();
            conReq.onload = function()
            {
                var json = conReq.response;
                console.log(json);
                document.querySelector('#result').textContent = json['conversion'];
            }
        }
    </script>

    </body>
</html>

<!-- document.querySelector("#convert").value
     + '&to=' + document.querySelector("#convert").to + '&from=' + document.querySelector("#convert").from
-->